[package]
name = "zk_snark"
version = "0.1.0"
authors = ["==replace-all <=>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"